use_frameworks!

target 'MapCache_Example' do
  pod 'MapCache', :path => '../'

  target 'MapCache_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs/Swift','~> 8.0.0'
    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 9.0.0-rc.3'
  end
end
