use_frameworks!

target 'MapCache_Example' do
  pod 'MapCache', :path => '../'

  target 'MapCache_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
