name: Documentation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Jazzy
        run: gem install jazzy

      - name: Generate documentation
        run: jazzy

      - name: Commit and push documentation
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update documentation"
          git push
