name: Swift

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: environment info
      run: |
        swift --version
        xcodebuild -version
    - name: Resolve package dependencies
      run: |
        swift package resolve
    - name: Test package
      run: |
        swift test --parallel
